"""Exploratory data analysis of the support dataset → ``docs/eda.md``.

Covers structured data (SQL + pandas aggregations) and unstructured text (lengths, discriminative
terms per category, PII prevalence). Run after ``atlas build-db``:  python scripts/eda.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

from atlas.db import read_only_query
from atlas.ml.classifier import clean_text
from atlas.security.pii import mask_pii

OUT = Path("docs/eda.md")


def md_table(df: pd.DataFrame, index: bool = True) -> str:
    df = df.reset_index() if index else df
    head = "| " + " | ".join(map(str, df.columns)) + " |"
    sep = "|" + "---|" * len(df.columns)
    rows = ["| " + " | ".join(map(str, r)) + " |" for r in df.itertuples(index=False)]
    return "\n".join([head, sep, *rows])


def main() -> None:
    t = read_only_query("SELECT t.*, c.tier FROM tickets t JOIN customers c USING (customer_id)")
    t["created_at"] = pd.to_datetime(t["created_at"])
    o = read_only_query("SELECT * FROM orders")
    sla = {"urgent": 8, "high": 24, "medium": 48, "low": 120}
    t["sla_breached"] = t["resolution_hours"] > t["priority"].map(sla)

    parts = [
        "# Exploratory Data Analysis\n",
        f"_Generated by `scripts/eda.py` · {len(t):,} tickets · {len(o):,} orders_\n",
    ]

    parts.append("## 1. Data quality\n")
    nulls = t.isna().mean().mul(100).round(1)
    parts.append(md_table(nulls[nulls > 0].rename("% null").rename_axis("column").to_frame()))
    parts.append(
        "\nNulls are expected: `resolution_hours`/`csat` only exist for resolved tickets.\n"
    )

    parts.append("## 2. Target distributions\n")
    dist = pd.concat(
        [
            t["category"].value_counts(normalize=True).mul(100).round(1),
        ],
        axis=1,
    ).rename(columns={"proportion": "% tickets"})
    parts.append(md_table(dist))
    parts.append("\nModerate imbalance → models use `class_weight='balanced'` and macro-F1.\n")
    parts.append(
        md_table(pd.crosstab(t["priority"], t["tier"], normalize="columns").mul(100).round(1))
    )
    parts.append(
        "\nGold customers skew to higher priorities → `tier` is a useful priority feature.\n"
    )

    parts.append("## 3. Time series\n")
    daily = t.set_index("created_at").resample("D").size()
    weekday = daily.groupby(daily.index.day_name()).mean().round(1)
    parts.append(md_table(weekday.rename("avg tickets/day").rename_axis("weekday").to_frame()))
    parts.append(
        f"\nWeekly seasonality is strong (Mondays ≈ {weekday.max():.0f}/day vs Sundays "
        f"≈ {weekday.min():.0f}/day), so the incident detector adjusts for weekday. "
        "Incidents are spikes in a single category, so they are detected per category "
        "(see `atlas.ml.anomaly`), not on total volume.\n"
    )

    parts.append("## 4. Operations: SLA and satisfaction\n")
    by_breach = t.groupby("sla_breached")["csat"].mean().round(2).rename("avg CSAT")
    parts.append(md_table(by_breach.to_frame()))
    corr = t[["resolution_hours", "csat"]].corr(method="spearman").iloc[0, 1]
    parts.append(
        f"\nSpearman(resolution_hours, csat) = **{corr:.2f}**: raw hours barely matter, but "
        "**breaching the SLA** drops CSAT by more than a point. Getting the *priority* right "
        "(and therefore the SLA clock) is what protects satisfaction.\n"
    )
    late = (
        o.dropna(subset=["delivered_at"])
        .assign(
            late=lambda d: (
                pd.to_datetime(d["delivered_at"]) > pd.to_datetime(d["estimated_delivery"])
            )
        )
        .groupby("carrier")["late"]
        .mean()
        .mul(100)
        .round(1)
        .sort_values(ascending=False)
    )
    parts.append(md_table(late.rename("% late").to_frame()))

    parts.append("\n## 5. Unstructured text\n")
    lengths = t["body"].str.len()
    parts.append(
        f"Ticket length: median **{lengths.median():.0f}** chars, "
        f"p95 **{lengths.quantile(0.95):.0f}** chars.\n"
    )
    pii = t["body"].map(lambda x: tuple(sorted(mask_pii(x).found)))
    pii_rate = (pii.map(len) > 0).mean() * 100
    parts.append(
        f"**{pii_rate:.1f}%** of tickets contain personal data (CPF / e-mail / phone) → "
        "masked before training, retrieval, logging and any LLM call (LGPD).\n"
    )

    vec = TfidfVectorizer(ngram_range=(1, 2), min_df=5, strip_accents="unicode")
    X = vec.fit_transform(clean_text(t["body"]))
    vocab = np.array(vec.get_feature_names_out())
    rows = []
    for cat in sorted(t["category"].unique()):
        mask = (t["category"] == cat).to_numpy()
        diff = np.asarray(X[mask].mean(axis=0) - X[~mask].mean(axis=0)).ravel()
        rows.append(
            {"category": cat, "most discriminative terms": ", ".join(vocab[np.argsort(-diff)[:8]])}
        )
    parts.append(md_table(pd.DataFrame(rows), index=False))
    parts.append(
        "\nTerms are highly category-specific, which is why a linear TF-IDF model is a strong, "
        "cheap and explainable baseline before reaching for an LLM classifier.\n"
    )

    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
